### ISSUE TITLE
执行注册文件报错，请问这个怎么解决啊？

### ISSUE THREAD

**Issue by hjh0915** [Filifun/heygen-auto-register#2]
~$ python register.py
Traceback (most recent call last):
  File "/home/jonna/heygen-auto-register/register.py", line 11, in <module>
    from app.captcha_resolver import CaptchaResolver
  File "/home/jonna/heygen-auto-register/app/captcha_resolver.py", line 2, in <module>
    from app.settings import CAPTCHA_RESOLVER_API_KEY, CAPTCHA_RESOLVER_API_URL
  File "/home/jonna/heygen-auto-register/app/settings.py", line 9, in <module>
    CAPTCHA_RESOLVER_API_KEY = env.str('CAPTCHA_RESOLVER_API_KEY')
  File "/home/jonna/.pyenv/versions/py310/lib/python3.10/site-packages/environs/__init__.py", line 116, in method
    raise EnvError(f'Environment variable "{proxied_key or parsed_key}" not set')
environs.EnvError: Environment variable "CAPTCHA_RESOLVER_API_KEY" not set

**Comment by Filifun** [comment]
配置文件赋值 env.str('CAPTCHA_RESOLVER_API_KEY')
app.settings import CAPTCHA_RESOLVER_API_KEY, CAPTCHA_RESOLVER_API_URL
